name: deploy-slides

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, builds the slides, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt



    # Build the slides
    - name: Build the slides
      run: |
        cd slides
        mkdir html
        jupytext README_slides.md --to ipynb
        jupyter nbconvert README_slides.ipynb --to slides --SlidesExporter.reveal_theme=solarized --stdout > html/index.html

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: slides/html
